version: "3"

services:
  mysql:
    container_name: mysql_overssl
    image: mysql
    volumes:
      - ./settings/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./data:/var/lib/mysql
      - ../OpenSSL_Certifies/certs:/etc/certs
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
